(* Base CSS Types: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types *)

nonprop-positive-integer = positive-integer ;

nonprop-angle      = any-number ( 'deg' | 'grad' | 'rad' | 'turn' ) ;
nonprop-flex       = any-number 'fr' S ;
nonprop-frequency  = any-number ( 'Hz' | 'kHz' ) S ;
nonprop-integer    = integer ;
nonprop-length     = any-number length-unit S
                   | '0' S ;
nonprop-number     = any-number S ;
nonprop-percentage = any-number '%' S ;
nonprop-resolution = any-number ( 'dpi' | 'dpcm' | 'dppx' | 'px' ) S ;
nonprop-time       = any-number ( 's' | 'ms' ) S ;

nonprop-ratio      = positive-integer '/' positive-integer ;

nonprop-string = quoted-string ;

(* https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident *)
nonprop-custom-ident = #'(?:[A-Za-z_]|-[A-Za-z_]|\\[0-9A-F]{1,6})(?:[A-Za-z0-9_-]|\\[0-9A-F]{1,6})*' S ;

(* TODO: improve urls: https://developer.mozilla.org/en-US/docs/Web/CSS/url *)
(*
nonprop-url = ( 'url(' url ')' S | 'url("' url '")' S )
            / 'url(' quoted-string ')' S;
*)
nonprop-url = 'url(' quoted-string ')' S;


nonprop-unicode-range = #'U[+](?:[0-9A-Fa-f]{1,4}-[0-9A-Fa-f]{1,4}|[0-9A-Fa-f?]{1,4})'
                        ( ',' S nonprop-unicode-range )* ;

nonprop-ident-token = "STUB_ident_token" ;
nonprop-declaration = css-declaration ;

nonprop-charset = charset ;

(* non-standard needed by font-face at-rules *)
(* TODO: are these bugs? *)

nonprop-font-variant = prop-font-variant ;
nonprop-font-feature-settings = prop-font-feature-settings ;
nonprop-font-variation-settings = prop-unknown ;
nonprop-font-stretch = prop-font-stretch ;
nonprop-font-weight = prop-font-weight ;
nonprop-font-style = prop-font-style ;


(* standard nonprop -> prop mappings *)
(* TODO: are these bugs? *)

nonprop-top = prop-top ;
nonprop-bottom = prop-bottom ;
nonprop-left = prop-left ;
nonprop-right = prop-right ;


(* Other Misc Missing *)
(* TODO: figure out why these are missing. *)

nonprop-hex-color = #'#[0-9A-Fa-f]{3}' S
                  | #'#[0-9A-Fa-f]{6}' S ;

nonprop-id-selector = nonprop-custom-ident ;
nonprop-ident = nonprop-custom-ident ;
nonprop-dimension = nonprop-resolution ;

func-path = "STUB_func_path" ;
nonprop-an-plus-b = "STUB_an_plus_b" ;
nonprop-any-value = "STUB_any_value" ;
nonprop-attr-name = "STUB_attr_name" ;
nonprop-attr-fallback = "STUB_attr_fallback" ;
nonprop-clip-style = "STUB_clip_style" ;
nonprop-custom-property-name = "STUB_custom_property" ;
nonprop-declaration-value = "STUB_declaration_value" ;
nonprop-function-token = "STUB_flex_function_token" ;
nonprop-mask-attachment = "STUB_mask_attachment" ;
nonprop-name-repeat = "STUB_name_repeat" ;
nonprop-string-token = "STUB_string_token" ;
nonprop-x = "11" ;
nonprop-y = "11" ;


(* TODO: from at-rule descriptors *)

nonprop-counter-system = "STUB_counter_system" ;
nonprop-counter-symbols = "STUB_counter_symbols" ;
nonprop-additive-symbols = "STUB_additive_symbols" ;
nonprop-negative-symbol = "STUB_negative_symbol" ;
nonprop-prefix = "STUB_prefix" ;
nonprop-suffix = "STUB_suffix" ;
nonprop-range = "STUB_range" ;
nonprop-padding = "STUB_padding" ;
nonprop-speak-as = "STUB_speak_as" ;
nonprop-page-body = "STUB_page_body" ;

