html = doctype? comment-or-space* '<html' (<rS> html-attribute)* '>' <S> head? body '</html>' <S>

doctype = '<!DOCTYPE html>' <S>

head = '<head>' <S> head-elements* '</head>' <S>

head-elements = title
              | meta
              | link
              | comment-or-space

title = '<title' (<rS> title-attribute)* '>' content* '</title>' <S>
meta = '<meta' (<rS> meta-attribute)* '>' <S>
link = '<link' (<rS> link-attribute)* '>' <S>

body = '<body' (<rS> body-attribute)* '>' (element | content)* '</body>' <S>

comment-or-space = comment | <S>

